import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import Providers from "./providers";
import BottomNavBar from "@/components/bottom-navbar";

const inter = Inter({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "Mmeko | %s",
    default: "Mmeko - Welcome"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-background`}>
        <Providers>
          <main className="flex overflow-hidden h-screen">
            <Sidebar />
            <div className="w-full grid grid-cols-1 grid-rows-[auto_1fr_auto] overflow-hidden">
              <Navbar />
              <div className="scrollbar pt-14 overflow-y-auto ">
                <div className="max-w-[80%] mx-auto">{children}</div>
              </div>
              <BottomNavBar />
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
