import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import Providers from "./providers";
import BottomNavBar from "@/components/bottom-navbar";

const inter = Inter({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mmeko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-background`}>
        <Providers>
          <main className="flex min-h-screen">
            <Sidebar />
            <div className="w-full">
              <Navbar />
              <div className="pt-14 mx-auto overflow-hidden">{children}</div>
              <BottomNavBar />
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
